name: effects_sdk_camera_windows
description: A Flutter plugin for getting information about and controlling the camera on Windows with Effects SDK.
repository: https://github.com/EffectsSDK/flutter-packages/tree/main/packages/camera/effects_sdk_camera_windows
publish_to: none
issue_tracker:
version: 0.2.1+5

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera
    platforms:
      windows:
        pluginClass: EffectsSDKCameraWindows
        dartPluginClass: EffectsSDKCameraWindows

dependencies:
  image: ^4.0.15
  camera_platform_interface:
    git:
      url: https://github.com/EffectsSDK/flutter-packages
      ref: effects-sdk-camera-win
      path: packages/camera/camera_platform_interface
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
